#m master torb coniguration
---
domain:   localhost:4567
database: "sqlite:///tmp/db"
salt:     la borra? la barra!

pages:
  home:           home.haml
  session.create: session.create.haml

puppets:
  "localhost:3000": whatever

blacklist: []
