#m master torb coniguration
---
domain:   internet
database: "sqlite::memory:" # for testing purposes or standalone running :memory: is the best choice
salt:     la borra? la barra!

pages:
  home:           home.haml
  session.create: session.create.haml

puppets:
  "localhost:3000": whatever

blacklist: []
