source :rubygems

# web server, I suggest thin
gem 'thin'

# core
gem 'sinatra'
gem 'haml'
gem 'datamapper'
gem 'json'
gem 'mechanize'
gem 'memoized'

# depending on database
gem 'dm-sqlite-adapter'
# gem 'dm-postgres-adapter'
